### ISSUE TITLE
How to Setup Google Authentication

### ISSUE THREAD

**Issue by ilovefreesw** [MarconLP/snapify#14]
I am getting this:

![image](https://github.com/MarconLP/snapify/assets/77317006/85c71a69-06fd-4f4c-ba9e-281890b56323)

![image](https://github.com/MarconLP/snapify/assets/77317006/3826f2b9-6cf9-4bf8-ab51-97b97b1bd70a)

I have set the redirect URL in Google Cloud Console: https://snapify-neon.vercel.app/api/auth/callback/google

Also, Postgres not working, I think it only works with MySQL ... you need to update the documentation.

**Comment by MarconLP** [comment]
Hi @ilovefreesw, did you follow the same instructions as shown in [this video](https://www.youtube.com/watch?v=HtJKUQXmtok), and added the `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` to the `.env` file?

That's correct Prisma is configured to use a MySQL database in [this file](https://github.com/MarconLP/snapify/blob/main/prisma/schema.prisma#L10).

**Comment by ilovefreesw** [comment]
OfCourse I have added client ID and client secret. For me even GitHub auth is not working. But I think it is not the problem with code but something at my end. I will have to look further.

Here you are telling to provision Postgres...better change it to MySQL: https://github.com/MarconLP/snapify/blob/ab9878b10c2dc3579d41a3bf126acc7937bda4b5/README.md?plain=1#L60

**Comment by ilovefreesw** [comment]
OfCourse I have added client ID and client secret. For me even the GitHub auth is not working. But I think it is not the problem with code but something at my end. I will have to look further.

Here you are telling to provision Postgres...better change it to MySQL: https://github.com/MarconLP/snapify/blob/ab9878b10c2dc3579d41a3bf126acc7937bda4b5/README.md?plain=1#L60

**Comment by MarconLP** [comment]
I've modified the instructions to mention MySQL rather than Postgres. Thanks for reporting that! https://github.com/MarconLP/snapify/commit/e9515bb068cb82722bc49861ce808cf6ecbcde3a
