### ISSUE TITLE
Modify the Navbar .

### ISSUE THREAD

**Issue by Aarav238** [MarconLP/snapify#24]
I would like to modify the navbar of the website. 
![image](https://github.com/MarconLP/snapify/assets/95538627/792945c9-e8bd-4b73-8b76-f3584522822d)

**Comment by MarconLP** [comment]
Hey @Aarav238, could you explain what exactly you would change and what purpose that would have?

**Comment by Aarav238** [comment]
Yeah I would like to add the name of website with its logo , and change some font weight and some effects which make it more attractive .

**Comment by MarconLP** [comment]
Sorry, but the current navbar design is fine.
